### ISSUE TITLE
ohm-grammar.ohm not hightlighted properly

### ISSUE THREAD

**Issue by pdubroy** [nfischer/vim-ohm#1]
I'm not a Vim user, but I wanted to give this a try anyways :-) After following the installation instructions, tried opening [ohm-grammar.ohm](https://github.com/cdglabs/ohm/blob/master/src/ohm-grammar.ohm), and it looked like this: ![ohm-grammar.ohm highlighting](https://cloud.githubusercontent.com/assets/17293/12550543/c2f3de74-c364-11e5-9d3c-dd91bc99970c.png)

The top bit looks great, but something in the definition of the `Alt` rule seems to confused it. I don't know anything about regular expressions in Vim, but is it possible the problem is that is greedily looking for a matching close paren?

**Comment by nfischer** [comment]
@pdubroy thanks for reporting the issue! I'm seeing the bug too. And yes, it looks like it's related to something like that. I'll see if I can have a fix out soon.

Also, on an unrelated note, you might like the colors better if you add `set background=dark` to your vimrc (I'll add that as an optional step to the installation).

**Comment by nfischer** [comment]
This should be fixed in #2 (now merged into master). For now, multi-line parentheses-descriptions won't get properly, only single-line. I'll see if I can come up with a fix that works for multi-line as well (although that might be tough with regex).
